#ifndef STM32F4XX_TIMER_REGS
#define  STM32F4XX_TIMER_REGS

#define TIMER2_BASE 0x40000000

#define TIMER_GLUE(s,n,m) s ## n ## m
#define TIMER_BASE(n) TIMER_GLUE(TIMER,n,_BASE)


#define r_CORTEX_M_TIM2CR1      REG_ADDR(TIMER_BASE(2)+0x00)
#define r_CORTEX_M_TIM2CR2      REG_ADDR(TIMER_BASE(2)+0x04)
#define r_CORTEX_M_TIM2SMCR     REG_ADDR(TIMER_BASE(2)+0x08)
#define r_CORTEX_M_TIM2DIER     REG_ADDR(TIMER_BASE(2)+0x0C)
#define r_CORTEX_M_TIM2SR       REG_ADDR(TIMER_BASE(2)+0x10)
#define r_CORTEX_M_TIM2EGR      REG_ADDR(TIMER_BASE(2)+0x14)
#define r_CORTEX_M_TIM2CCMR1    REG_ADDR(TIMER_BASE(2)+0x18)
#define r_CORTEX_M_TIM2CCMR2    REG_ADDR(TIMER_BASE(2)+0x1C)
#define r_CORTEX_M_TIM2CCER     REG_ADDR(TIMER_BASE(2)+0x20)
#define r_CORTEX_M_TIM2CNT      REG_ADDR(TIMER_BASE(2)+0x24) 
#define r_CORTEX_M_TIM2PSC      REG_ADDR(TIMER_BASE(2)+0x28) 
#define r_CORTEX_M_TIM2ARR      REG_ADDR(TIMER_BASE(2)+0x2c) 
#define r_CORTEX_M_TIM2CCR1     REG_ADDR(TIMER_BASE(2)+0x34) 
#define r_CORTEX_M_TIM2CCR2     REG_ADDR(TIMER_BASE(2)+0x38) 
#define r_CORTEX_M_TIM2CCR3     REG_ADDR(TIMER_BASE(2)+0x3c) 
#define r_CORTEX_M_TIM2CCR4     REG_ADDR(TIMER_BASE(2)+0x40) 
#define r_CORTEX_M_TIM2DCR      REG_ADDR(TIMER_BASE(2)+0x48) 
#define r_CORTEX_M_TIM2DMAR     REG_ADDR(TIMER_BASE(2)+0x4c) 
#define r_CORTEX_M_TIM2OR       REG_ADDR(TIMER_BASE(2)+0x50) 

#endif // STM32F4XX_TIMER_REGS
